version: "3.4"

services:

  app:
    container_name: app
    build:
      context: .
      args:
        - ENVIRONMENT=dev
    ports:
      - 8000:8000
    volumes:
      - ${PWD}:/x
    environment:
      - ENVIRONMENT=dev
      - FACEBOOK_ACCESS_TOKEN=token
    command: flask --app=app.main:app run --host=0.0.0.0 --port=8000 --debug
